server {
    listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
  location /api/ {
    proxy_pass https://inventoryflowbackend.azurewebsites.net; # for production
    # proxy_pass http://backend:3000; # for development
  }
}